### ISSUE TITLE
Transaction failed with 'Transaction Service Name not found in configuration' in multi threaded environment

### ISSUE THREAD

**Issue by snehavikhar** [yugandharproject/YugandharMDMHub#1]
The transaction failed with below error while in multi threaded environment

100 - Transaction Service Name not found in configuration

error log
+++++++++++++
2018-04-12 16:28:29,881 2110027 [default task-21] INFO  YugandharPerfErrorSummaryLogger - createLegalEntity|admin|admin|null|null|null|1c6ac272-0d69-4ac2-a87d-3f896d0a7519|FAIL|null|1002|Transaction Service Name not found in configuration

2018-04-12 16:28:29,882 2110028 [default task-21] DEBUG YugandharCommonLogger - After Execution of : com.yugandhar.rest.controller.RequestProcessor.processMessage Method

2018-04-12 16:28:29,883 2110029 [default task-21] ERROR YugandharCommonLogger - Execution FAILED for : com.yugandhar.rest.controller.RequestProcessor.processMessage Method with error:com.yugandhar.common.exception.YugandharCommonException

2018-04-12 16:28:30,095 2110241 [default task-21] ERROR YugandharCommonLogger - Transaction failed

com.yugandhar.common.exception.YugandharCommonException: null

 at com.yugandhar.common.util.CommonValidationUtil.populateErrorResponse(CommonValidationUtil.java:156)

 at com.yugandhar.common.util.CommonValidationUtil$$FastClassBySpringCGLIB$$740f699d.invoke(<generated>)

 at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)

 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)

 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

 at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)

 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)

 at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:47)

 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)

 at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)

 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)

 at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)

 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)

 at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)

 at com.yugandhar.common.util.CommonValidationUtil$$EnhancerBySpringCGLIB$$fe4d91e.populateErrorResponse(<generated>)

 at com.yugandhar.rest.controller.RequestProcessor.setServiceClassAndMethodName(RequestProcessor.java:322)

 at com.yugandhar.rest.controller.RequestProcessor.processMessage(RequestProcessor.java:96)

 at com.yugandhar.rest.controller.RequestProcessor$$FastClassBySpringCGLIB$$6a391649.invoke(<generated>)

 at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)

 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)

 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

 at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)

 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)

 at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:47)

 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)

 at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)

 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)

 at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)

 at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)

 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)

 at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)

 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)

 at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)

 at com.yugandhar.rest.controller.RequestProcessor$$EnhancerBySpringCGLIB$$792aa8e7.processMessage(<generated>)

 at com.yugandhar.rest.controller.DefaultJsonRESTController.YugandharRequestProcessor(DefaultJsonRESTController.java:63)

 at com.yugandhar.rest.controller.DefaultJsonRESTController$$FastClassBySpringCGLIB$$a1ee60d3.invoke(<generated>)

 at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)

 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)

 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

 at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)

 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)

 at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:47)

 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)

 at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)

 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)

 at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)

 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)

 at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)

 at com.yugandhar.rest.controller.DefaultJsonRESTController$$EnhancerBySpringCGLIB$$67e2f080.YugandharRequestProcessor(<generated>)

 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

 at java.lang.reflect.Method.invoke(Method.java:498)

 at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)

 at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)

 at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)

 at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)

 at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)

 at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)

 at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)

 at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)

 at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)

 at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)

 at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)

 at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)

 at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

 at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)

 at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)

 at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)

 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

 at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)

 at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)

 at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)

 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

 at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)

 at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)

 at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)

 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

 at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)

 at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)

 at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:117)

 at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:61)

 at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:92)

 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

 at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:110)

 at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)

 at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)

 at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)

 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

 at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)

 at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)

 at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)

 at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)

 at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)

 at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)

 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

 at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)

 at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)

 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

 at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)

 at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)

 at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)

 at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)

 at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)

 at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)

 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

 at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)

 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

 at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)

 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

 at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)

 at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)

 at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)

 at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)

 at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)

 at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)

 at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)

 at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)

 at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)

 at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)

 at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)

 at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)

 at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)

 at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)

 at io.undertow.server.Connectors.executeRootHandler(Connectors.java:326)

 at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:812)

 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

 at java.lang.Thread.run(Thread.java:745)

2018-04-12 16:28:30,099 2110245 [default task-21] DEBUG YugandharCommonLogger - Execution of : com.yugandhar.common.util.CommonValidationUtil.createCommonValidationResponseFromYugException Method - Started

2018-04-12 16:28:30,100 2110246 [default task-21] DEBUG YugandharCommonLogger - After Execution of : com.yugandhar.common.util.CommonValidationUtil.createCommonValidationResponseFromYugException Method

2018-04-12 16:28:30,100 2110246 [default task-21] DEBUG YugandharCommonLogger - After Execution of : com.yugandhar.rest.controller.DefaultJsonRESTController.YugandharRequestProcessor Method

2018-04-12 16:28:30,459 2110605 [default task-30] DEBUG YugandharCommonLogger - After Execution of : com.yugandhar.mdm.config.txnregistry.ConfigTxnRegistryRepository.findByBusinessKeyActive Method

2018-04-12 16:28:30,460 2110606 [default task-30] INFO  YugandharMQRequestResponseLogger - Printing reqConfigTxnRegistryDO: TxnMessageId|5416bca5-4a5b-472e-8aeb-43dfbc2acc5acreateLegalEntityACTIVEcom.yugandhar.mdm.composite.service.CreateLegalEntityService

2018-04-12 16:28:30,460 2110606 [default task-30] DEBUG Yugandha

**Comment by snehavikhar** [comment]
Found that the issue is because of singleton rest controller. Needs to add @Scope(value = "prototype") at the controller scope level to create different instance of the rest controller per request.

**Comment by snehavikhar** [comment]
Issue will be resolved in Version 2.0.0.RELEASE
